version: '3.9'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASS}
    ports:
      - '1433:1433'
    volumes:
      - sql-volume:/var/opt/mssql
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-volume:/data
volumes:
  sql-volume:
  redis-volume:
