version: '3.9'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASS}
    ports:
      - '1433:1433'
    volumes:
      - sql-volume:/var/opt/mssql
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-volume:/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
      - '9411:9411'
    volumes:
      - jaeger-volume:/tmp
  keeper-synchronizer:
    build:
      context: .
      dockerfile: src/Keeper.Synchronizer/Dockerfile
    environment:
    - ConnectionStrings__DatabaseContext=Server=sql-server;Database=Keeper;User Id=sa;Password=${SQL_SERVER_PASS};
    - ConnectionStrings__Redis=redis
    - ConnectionStrings__Jaeger=jaeger
volumes:
  sql-volume:
  redis-volume:
  jaeger-volume:
