// <auto-generated />
using System;
using Keeper.ConsoleApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Keeper.Core.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211016074621_AddKickingStatistics")]
    partial class AddKickingStatistics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Keeper.Core.Database.NflKickingStatistics", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldGoal0To19Yards")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldGoal20To29Yards")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldGoal30To39Yards")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldGoal40To49Yards")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldGoal50PlusYards")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatMade")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "Season", "Week");

                    b.ToTable("NflKickingStatistics");
                });

            modelBuilder.Entity("Keeper.Core.Database.NflPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NflPlayers");
                });

            modelBuilder.Entity("Keeper.Core.Database.NflPlayerStatistics", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FantasyPoints")
                        .HasColumnType("REAL");

                    b.HasKey("PlayerId", "Season", "Week");

                    b.ToTable("NflPlayerStatistics");
                });

            modelBuilder.Entity("Keeper.Core.Database.NflKickingStatistics", b =>
                {
                    b.HasOne("Keeper.Core.Database.NflPlayer", "Player")
                        .WithMany("NflKickingStatistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Keeper.Core.Database.NflPlayerStatistics", b =>
                {
                    b.HasOne("Keeper.Core.Database.NflPlayer", "Player")
                        .WithMany("PlayerStatistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Keeper.Core.Database.NflPlayer", b =>
                {
                    b.Navigation("NflKickingStatistics");

                    b.Navigation("PlayerStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
